import type { Banner } from "@/lib/types";

// This file is generated by scripts/build-banners.mjs.
// Edit data/banner-intake/banners.md, then run: npm run banners:build
export const banners: Banner[] = [
  {
    id: "gaga-cancel",
    title: "Lady gaga再次临开场取消演唱会",
    dek: "首谈支气管炎 不管粉丝钱包死活！",
    body: "美国迈阿密原定4月18日晚，Lady Gaga「Mayhem Ball」巡演重磅开唱，全城粉丝满怀期待、氛围沸腾。开场仅剩5分钟之际，Lady Gaga突发官宣紧急取消本场演出，并向全球歌迷诚挚致歉。她坦言声带负荷严重超标，经医生与声乐教练专业评估，严禁登台演出。秉持现场真唱的艺术坚守，为避免声带造成永久性损伤，无奈忍痛取消巡演。",
    imageSrc: "/assets/banners/gaga-cancel.png",
    sourceLabel: "怪兽之母再次遛粉",
    sourceUrl: "https://www.google.com/search?q=Lady+Gaga+cancelled+concert+illness",
    color: "#b8ff9c",
  },
  {
    id: "olivia-dropdead",
    title: "Olivia为窑冠单不择手段",
    dek: "行业里有一些很mean的前辈",
    body: "新人热单选择德州与olivia三年回归便秘作首单dropdead摔死对撞，窑鸡官方下场求药剂迷粉丝购买单曲以夺冠单，官方下场欺负后辈恭喜窑母鸡reputation有",
    imageSrc: "/assets/banners/olivia-dropdead.png",
    sourceLabel: "新疆棉不要脸",
    sourceUrl: "https://www.google.com/search?q=Olivia+Rodrigo+new+single+Dropdead+Choosing+Texas",
    color: "#ffd2ea",
  },
  {
    id: "ariana-petal",
    title: "Ariana 7.31 回归",
    dek: "AG8《Petal》官宣择日开炸",
    body: "AG8《Petal》定档 7.31全世界的小炸弹都来支持啦，炸天尊开榜封神！超高人气天后Ariana定于7月31日强势回归，暌违许久再度站上舞台，牵动全球歌迷目光。粉丝早早守候蹲守官宣，全网话题热度飙升，一场视听盛宴即将如约而至",
    imageSrc: "/assets/banners/ariana-petal.png",
    sourceLabel: "A女帝新专",
    sourceUrl: "https://www.universalmusic.ca/press-releases/ariana-grande-announces-eighth-studio-album-petal-to-be-released-july-31/",
    color: "#eaff3d",
  },
  {
    id: "shunyanzi",
    title: "孙麻子被金曲奖婉拒",
    dek: "Thank you chanel来到了金曲奖颁奖舞台",
    body: "当年买榜诈骗的“天后”麻子，复出搞了张《跳舞的梵谷》，结果金曲奖连个通类提名都摸不到，就俩边角提名凑数，简直笑死人。麻子落选当晚直接破防发小作文，搁这卖惨说“我的努力不会因为落选被毁掉”，合着没拿奖全是金曲奖瞎了，跟专辑烂不烂半毛钱没有是吧？品味差的不得了，又喜欢装文艺，揭开遮羞布，归来还是素人麻子。乐评人都看不过去了，直接戳破她的矫情：这张专辑都烂到接二连三掉粪坑快埋脖子了，换我是她，躲都来不及，还好意思半夜出来哭唧唧？情怀滤镜碎得渣都不剩，这波纯纯是玻璃心+烂作品双翻车，笑不活了",
    imageSrc: "/assets/banners/shunyanzi.png",
    sourceLabel: "麻子丢人",
    sourceUrl: "https://www.xiaohongshu.com/search_result?keyword=%25E5%25AD%2599%25E7%2587%2595%25E5%25A7%25BF%25E9%2587%2591%25E6%259B%25B2%25E5%25A5%2596&source=web_explore_feed",
    color: "#ffd2ea",
  },
];
