import type { Banner } from "@/lib/types";

// This file is generated by scripts/build-banners.mjs.
// Edit data/banner-intake/banners.md, then run: npm run banners:build
export const banners: Banner[] = [
  {
    id: "gaga-cancel",
    title: "Lady gaga再次临开场取消演唱会",
    dek: "首谈支气管炎 不管粉丝钱包死活！",
    body: "美国迈阿密原定4月18日晚，Lady Gaga「Mayhem Ball」巡演重磅开唱，全城粉丝满怀期待、氛围沸腾。开场仅剩5分钟之际，Lady Gaga突发官宣紧急取消本场演出，并向全球歌迷诚挚致歉。她坦言声带负荷严重超标，经医生与声乐教练专业评估，严禁登台演出。秉持现场真唱的艺术坚守，为避免声带造成永久性损伤，无奈忍痛取消巡演。",
    imageSrc: "/assets/banners/gaga-cancel.png",
    sourceLabel: "怪兽之母再次遛粉",
    sourceUrl: "https://www.google.com/search?q=Lady+Gaga+cancelled+concert+illness",
    color: "#b8ff9c",
  },
  {
    id: "olivia-the-cure",
    title: "the cure艺术已成！Pitchfork给出Best New Track",
    dek: "窑姐这次不是抢冠，是拿乐评打脸",
    body: "Olivia Rodrigo 新单《the cure》正式上线，Pitchfork 直接给出 Best New Track，评价其作为新专《You Seem Pretty Sad for a Girl So in Love》里的成熟推进。前作还在被嘲抢冠，这次窑姐干脆换赛道：不靠嘴硬，直接拿乐评和首日热度说话。《the cure》首日登顶 Spotify Global 和 US 榜，Pitchfork 也盖章艺术进化，同辈还在营销“回归”，窑姐已经把新声代作业本翻到下一页。",
    imageSrc: "/assets/banners/olivia-the-cure.png",
    sourceLabel: "Pitchfork盖章艺术已成",
    sourceUrl: "https://pitchfork.com/reviews/tracks/olivia-rodrigo-the-cure/",
    color: "#ffd2ea",
  },
  {
    id: "ariana-hate-love-me",
    title: "Ariana新单上线，冠单梦先碎一地",
    dek: "贷款第八冠，结果榜单不听粉丝祈福",
    body: "Ariana Grande 新单《hate that i made you love me》上线，作为《petal》预热单，Official Charts 还提前写着她要冲击第八支英国冠单，粉丝已经把花瓣铺到王座边。结果 Big Top 40 首周只落在第 5，连单曲冠军都没摸到，贷款“Chart Queen”当场变成花瓣掉地。Spotify 数据确实能打，但如果要拿“冠单回归”当叙事，那炸姐这次只能先把皇冠放回购物车。",
    imageSrc: "/assets/banners/ariana-hate-love-me.png",
    sourceLabel: "贷款第八冠失败样本",
    sourceUrl: "https://www.officialcharts.com/chart-news/new-music-friday-songs-single-albums-may-29-2026/",
    color: "#eaff3d",
  },
  {
    id: "shunyanzi",
    title: "孙麻子被金曲奖婉拒",
    dek: "Thank you chanel来到了金曲奖颁奖舞台",
    body: "当年买榜诈骗的“天后”麻子，复出搞了张《跳舞的梵谷》，结果金曲奖连个通类提名都摸不到，就俩边角提名凑数，简直笑死人。麻子落选当晚直接破防发小作文，搁这卖惨说“我的努力不会因为落选被毁掉”，合着没拿奖全是金曲奖瞎了，跟专辑烂不烂半毛钱没有是吧？品味差的不得了，又喜欢装文艺，揭开遮羞布，归来还是素人麻子。乐评人都看不过去了，直接戳破她的矫情：这张专辑都烂到接二连三掉粪坑快埋脖子了，换我是她，躲都来不及，还好意思半夜出来哭唧唧？情怀滤镜碎得渣都不剩，这波纯纯是玻璃心+烂作品双翻车，笑不活了",
    imageSrc: "/assets/banners/shunyanzi.png",
    sourceLabel: "麻子丢人",
    sourceUrl: "https://www.xiaohongshu.com/search_result?keyword=%25E5%25AD%2599%25E7%2587%2595%25E5%25A7%25BF%25E9%2587%2591%25E6%259B%25B2%25E5%25A5%2596&source=web_explore_feed",
    color: "#ffd2ea",
  },
];
