import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const intakePath = path.join(rootDir, "data/banner-intake/banners.md");
const outputPath = path.join(rootDir, "data/banners.ts");
const imageDir = path.join(rootDir, "public/assets/banners");

const fieldMap = new Map([
  ["id", "id"],
  ["标题", "title"],
  ["副标题", "dek"],
  ["正文", "body"],
  ["图片文件名", "imageFile"],
  ["来源标签", "sourceLabel"],
  ["来源链接", "sourceUrl"],
  ["颜色", "color"],
  ["是否启用", "enabled"],
  ["排序", "order"],
]);

const requiredFields = [
  "id",
  "title",
  "dek",
  "body",
  "imageFile",
  "sourceLabel",
  "sourceUrl",
  "color",
];

function parseBannerBlocks(markdown) {
  return markdown
    .split(/^## Banner\s*$/m)
    .map((block) => block.trim())
    .filter(Boolean)
    .map(parseBannerBlock);
}

function parseBannerBlock(block) {
  const banner = {};

  for (const rawLine of block.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const separatorIndex = line.indexOf("：") >= 0 ? line.indexOf("：") : line.indexOf(":");
    if (separatorIndex < 0) continue;

    const rawKey = line.slice(0, separatorIndex).trim();
    const rawValue = line.slice(separatorIndex + 1).trim();
    const key = fieldMap.get(rawKey);

    if (key) {
      banner[key] = rawValue;
    }
  }

  return banner;
}

function assertValidBanners(banners) {
  const ids = new Set();

  for (const banner of banners) {
    for (const field of requiredFields) {
      if (!banner[field]) {
        throw new Error(`Banner "${banner.id || "未命名"}" 缺少字段：${field}`);
      }
    }

    if (ids.has(banner.id)) {
      throw new Error(`Banner id 重复：${banner.id}`);
    }

    ids.add(banner.id);

    const imagePath = path.join(imageDir, banner.imageFile);
    if (!existsSync(imagePath)) {
      throw new Error(`Banner "${banner.id}" 图片不存在：${imagePath}`);
    }
  }
}

function isEnabled(value) {
  const normalized = String(value || "是").trim().toLowerCase();
  return !["否", "no", "false", "0", "disabled"].includes(normalized);
}

function orderOf(banner, index) {
  const parsed = Number.parseFloat(banner.order || "");
  return Number.isFinite(parsed) ? parsed : index;
}

function toTsString(value) {
  return JSON.stringify(value);
}

function renderBannersTs(banners) {
  const items = banners
    .map(
      (banner) => `  {
    id: ${toTsString(banner.id)},
    title: ${toTsString(banner.title)},
    dek: ${toTsString(banner.dek)},
    body: ${toTsString(banner.body)},
    imageSrc: ${toTsString(`/assets/banners/${banner.imageFile}`)},
    sourceLabel: ${toTsString(banner.sourceLabel)},
    sourceUrl: ${toTsString(banner.sourceUrl)},
    color: ${toTsString(banner.color)},
  }`,
    )
    .join(",\n");

  return `import type { Banner } from "@/lib/types";

// This file is generated by scripts/build-banners.mjs.
// Edit data/banner-intake/banners.md, then run: npm run banners:build
export const banners: Banner[] = [
${items},
];
`;
}

const parsedBanners = parseBannerBlocks(readFileSync(intakePath, "utf8"));
const enabledBanners = parsedBanners
  .map((banner, index) => ({ ...banner, __index: index }))
  .filter((banner) => isEnabled(banner.enabled))
  .sort((a, b) => orderOf(a, a.__index) - orderOf(b, b.__index));

assertValidBanners(enabledBanners);
writeFileSync(outputPath, renderBannersTs(enabledBanners), "utf8");

console.log(`Generated ${enabledBanners.length} banners -> data/banners.ts`);
