import type { Banner } from "@/lib/types";

// This file is generated by scripts/build-banners.mjs.
// Edit data/banner-intake/banners.md, then run: npm run banners:build
export const banners: Banner[] = [
  {
    id: "taylor-toy-story-5-theme",
    title: "Taylor进玩具箱，迪士尼也来坐大巴",
    dek: "《Toy Story 5》主题曲到手，交姐开始给牛仔娃娃续命",
    body: "Taylor Swift 为《Toy Story 5》写并演唱新歌《I Knew It, I Knew You》，Disney Press 还点名这是给 Jessie 的歌，6 月 5 日先发单曲，电影 6 月 19 日上。交姐这回不卖体育场烟花，转头给皮克斯玩具擦眼泪，粉丝可以说是回归 country roots，黑粉也能嘴一句“连玩具都要被她写进前任宇宙”。但迪士尼这张牌确实漂亮：小朋友听友情，大人听怀旧，Swiftie 听到最后还是会自动脑补彩蛋，玩具总动员还没上映，解读大军已经先开箱。",
    imageSrc: "/assets/banners/taylor-toy-story-5.png",
    sourceLabel: "Disney Press官宣主题曲",
    sourceUrl: "https://press.disney.co.uk/news/taylor-swift-announces-new-song-i-knew-it-i-knew-you-for-toy-story-5-single-drops-june-5",
    updatedAt: "2026-06-13",
    color: "#d9d0ff",
  },
  {
    id: "olivia-pitchfork-83-bna",
    title: "Olivia 8.3封神，Pitchfork递上王冠",
    dek: "Best New Album到手，窑姐把乐评打服",
    body: "Olivia Rodrigo 新专《you seem pretty sad for a girl so in love》拿到 Pitchfork 8.3，并被盖上 Best New Album。这个分数不是粉丝自封“艺术已成”，是乐评桌直接把章按脸上：从失恋小作文进化到 80 年代浪漫病房，把恋爱写成发烧、晕车和慢性消耗。之前还在嘲窑姐只会青春疼痛的人，现在要么承认她会写，要么继续嘴硬说 Pitchfork 也被收买。问题是 8.3 已经摆在桌上，嘴硬再大声，也只能算背景音。",
    imageSrc: "/assets/banners/olivia-girl-so-in-love-vinyl.png",
    sourceLabel: "Pitchfork 8.3 Best New Album",
    sourceUrl: "https://pitchfork.com/reviews/albums/olivia-rodrigo-you-seem-pretty-sad-for-a-girl-so-in-love/",
    updatedAt: "2026-06-13",
    color: "#ffd2ea",
  },
  {
    id: "ariana-hate-love-me",
    title: "Ariana贷款登基，榜单真给打款",
    dek: "皇冠刚放进购物车，结果订单居然成交",
    body: "Ariana Grande 新单《hate that i made you love me》上线前，Official Charts 已经把“冲击第八支英国冠单”的气氛铺到王座边，粉丝也早早把花瓣撒满红毯。最戏剧的是，这次榜单没有拆台，冠单真到账。炸姐不是没被贷款，是贷款竟然过审：粉丝立刻改口“女王回宫”，黑粉只能临时找补“含金量一般”。可榜首两个字已经落地，再嘴硬也只能站在门外说王冠不好看。",
    imageSrc: "/assets/banners/ariana-hate-love-me.png",
    sourceLabel: "第八支英国冠单兑现",
    sourceUrl: "https://www.officialcharts.com/chart-news/new-music-friday-songs-single-albums-may-29-2026/",
    updatedAt: "2026-06-13",
    color: "#eaff3d",
  },
  {
    id: "shunyanzi",
    title: "孙麻子被金曲奖婉拒",
    dek: "Thank you chanel来到了金曲奖颁奖舞台",
    body: "当年买榜诈骗的“天后”麻子，复出搞了张《跳舞的梵谷》，结果金曲奖连个通类提名都摸不到，就俩边角提名凑数，简直笑死人。麻子落选当晚直接破防发小作文，搁这卖惨说“我的努力不会因为落选被毁掉”，合着没拿奖全是金曲奖瞎了，跟专辑烂不烂半毛钱没有是吧？品味差的不得了，又喜欢装文艺，揭开遮羞布，归来还是素人麻子。乐评人都看不过去了，直接戳破她的矫情：这张专辑都烂到接二连三掉粪坑快埋脖子了，换我是她，躲都来不及，还好意思半夜出来哭唧唧？情怀滤镜碎得渣都不剩，这波纯纯是玻璃心+烂作品双翻车，笑不活了",
    imageSrc: "/assets/banners/shunyanzi.png",
    sourceLabel: "麻子丢人",
    sourceUrl: "https://www.xiaohongshu.com/search_result?keyword=%25E5%25AD%2599%25E7%2587%2595%25E5%25A7%25BF%25E9%2587%2591%25E6%259B%25B2%25E5%25A5%2596&source=web_explore_feed",
    updatedAt: "2026-06-01",
    color: "#ffd2ea",
  },
];
